import type { Metadata } from "next";
import { Amiri } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const amiri = Amiri({
  variable: "--font-amiri",
  subsets: ["arabic"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${amiri.variable}`} >
        <Navbar />

        {children}
      </body>
    </html>
  );
}
